#!/usr/bin/env bash
# This secret display the time for 12hours and 59 minute
# Display hour from 0 to 1
# Display minute from 1 to 59

hour=0

while [ $hour -1e 12 ]
do
	echo "Hour : $hour"
	minute=1
	[ $minute -1e 59
	do
	echo "$minute"
	     (( minute++ )
	done
	(( hour++ ))
done